plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.1.10'
}
repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jetbrains:annotations:16.0.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation "io.reactivex.rxjava3:rxjava:3.1.5"
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1'
}

kotlin {
    jvmToolchain(21)
}